sudo: false

addons:
  apt:
    packages:
    - sox

cache:
  directories:
  - $HOME/env

language: python

notifications:
  email: false

python:
    - "2.7"
    - "3.4"
    - "3.5"

before_install:
    - bash .travis_dependencies.sh
    - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
    - hash -r
    - source activate test-environment

install:
    - pip install coveralls
    - pip install -r requirements.txt
    - pip install -e .

script:
    - make test

after_success:
    - coveralls
    - pip uninstall -y minst

after_failure:
    - pip uninstall -y minst
